### ISSUE TITLE
Language switcher only works on home page

### ISSUE THREAD

**Issue by mtom55** [OpenWebAdvocacy/website#182]
## Type of Change
- [x ] Bug

## Summary
<img width="960" alt="image" src="https://github.com/user-attachments/assets/8d8f3a52-c8bd-48a3-819f-b6557aaf8a4c">

The language switcher doesn't work on other pages on the site, other than the home page

**Comment by shuuji3** [comment]
I can see the language switcher works as expected between translated pages. For example, both the "Home" and "Get Involved" pages have Spanish translations:
- Open Web Advocacy - https://open-web-advocacy.org/es/
- Involucrarte - Open Web Advocacy - https://open-web-advocacy.org/es/get-involved/#

I think this is an intuitive implementation.

On the other hand, the "Blog" page has no Spanish translation yet but it shows two links, both for the English page:

![screenshot of news page with language selector dialog showing English and Spanish](https://github.com/user-attachments/assets/3b07ce3b-714a-448c-8fb0-e75999d21624)
News - Open Web Advocacy - https://open-web-advocacy.org/blog/

I'd suggest either 1) showing only translated pages in the Languages selector dialog or 2) showing both language names but disabling the link to a non-existing page and adding some label or icon indicating that this page hasn't been translated yet.

Also, the Spanish home page has mixed links; some links navigate to the Spanish page and others to the English page. However, users cannot see clearly the difference between them. Maybe we can put a label such as `[en]` next to the links to an untranslated page.
