### ISSUE TITLE
Add focus trap to language version modal

### ISSUE THREAD

**Issue by gericci** [OpenWebAdvocacy/website#188]
## Type of Change
- [ ] Enhancement
- [ ] Content
- [ ] Improvement / Suggestion
- [x ] Bug (accessibility)
- [ ] Other (please clarify below)

## Summary
As the dialog for language versions has any focus trap, keyboard users will "leave" the dialog and continues to tab on main page, when she should stay on the dialog until it is closed

## Details
Add a script to prevent keyboard users to leave the dialog before closing it

**Comment by rejhgadellaa** [comment]
Shouldn't the `<dialog />` element take care of that when it's in modal-mode? That automatically makes the document inert (except for the dialog).

**Comment by jessbudd** [comment]
Has this issue already been completed? Focus trap appears to be working correctly for me

https://github.com/user-attachments/assets/51999f7a-6222-41ec-9c31-258e77ea530d

**Comment by sbesh91** [comment]
Closing this issue as it seems to work as expected.
