### ISSUE TITLE
Add open graph / twitter metadata

### ISSUE THREAD

**Issue by rejhgadellaa** [OpenWebAdvocacy/website#5]
The current site doesn't show a preview / snippet when sharing it via Twitter. I assume the same thing happens on Facebook and other platforms.

It looks like the template for the new site already has the parts to make it work, not sure if the necessary data is actually provided somewhere:
https://github.com/OpenWebAdvocacy/website/blob/main/src/_includes/partials/meta-info.njk

![image](https://user-images.githubusercontent.com/4703109/156937512-cf2d51b2-f232-4e48-aeb3-53514432c15f.png)

**Comment by thescientist13** [comment]
Good catch.  Not sure where the current site is hosted from, but we'll probably want to sync the text images for both until a final cutover can be made to this repo.

**Comment by mtom55** [comment]
https://github.com/open-web-advocacy/website << here's the current website if anyone's got time to do a push.

**Comment by capjamesg** [comment]
@mtom55 I shall take this on and file a PR.

**Comment by rejhgadellaa** [comment]
This has been addressed, closing issue.
